export const paths = {
  dashboard: "/admin/dashboard",
  settings: "/admin/settings",
  allTeam: "/admin/team",
  addMember: "/admin/team/add",
  editMember: "/admin/team/edit/:id",
  listTeamCategory: "/admin/team/category",
  addTeamCategory: "/admin/team/category/add",
  editTeamCategory: "/admin/team/category/edit/:id",
  allVolunteers: "/admin/volunteer",
  addVolunteer: "/admin/volunteer/add",
  editVolunteer: "/admin/volunteer/edit/:id",
  listVolunteerCategory: "/admin/volunteer/category",
  addVolunteerCategory: "/admin/volunteer/category/add",
  editVolunteerCategory: "/admin/volunteer/category/edit/:id",
  jobs: "/admin/jobs",
  addNewJob: "/admin/jobs/add",
  editJob: "/admin/jobs/edit",
};
