export const paths = {
  dashboard: "/admin/dashboard",
  partners:"/admin/partners",
  addPartner:"/admin/partners/add",
  editPartner:"/admin/partners/edit",
  settings: "/admin/settings",
  team: "/admin/team",
  addMember: "/admin/team/add",
  editMember: "/admin/team/edit", 
  allVolunteers: "/admin/volunteer",
  addVolunteer: "/admin/volunteer/add",
  editVolunteer: "/admin/volunteer/edit/:id",
  listVolunteerCategory: "/admin/volunteer/category",
  addVolunteerCategory: "/admin/volunteer/category/add",
  editVolunteerCategory: "/admin/volunteer/category/edit/:id",
  jobs: "/admin/jobs",
  addNewJob: "/admin/jobs/add",
  editJob: "/admin/jobs/edit",
  viewJob: "/admin/jobs/view",
};
