  // src/lib/rbac/permissions.ts
// ─────────────────────────────────────────────────────────────────────────────
// Single source of truth for permission keys and group categorizations.
// Used by:
//   - hooks/usePermissions.ts       (Permission type)
//   - components/PermissionGate.tsx (Permission type)
//   - UI/Admin Dashboard settings   (to map permissions into readable groups)
// ─────────────────────────────────────────────────────────────────────────────

export type Permission = string;

// ── Typed constants ───────────────────────────────────────────────────────────
// Use these in components instead of raw strings to catch typos at compile time.
export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  EXPORT_DASHBOARD_DATA: "EXPORT_DASHBOARD_DATA",

  // Team
  VIEW_TEAM: "VIEW_TEAM",
  CREATE_TEAM: "CREATE_TEAM",
  UPDATE_TEAM: "UPDATE_TEAM",
  DELETE_TEAM: "DELETE_TEAM",
  EXPORT_TEAM: "EXPORT_TEAM",

  // Team Categories
  VIEW_TEAMCATEGORIES: "VIEW_TEAMCATEGORIES",
  CREATE_TEAMCATEGORIES: "CREATE_TEAMCATEGORIES",
  UPDATE_TEAMCATEGORIES: "UPDATE_TEAMCATEGORIES",
  DELETE_TEAMCATEGORIES: "DELETE_TEAMCATEGORIES",

  // Volunteer Requests
  VIEW_VOLUNTEER_REQUEST: "VIEW_VOLUNTEER_REQUEST",
  UPDATE_VOLUNTEER_REQUEST: "UPDATE_VOLUNTEER_REQUEST",
  DELETE_VOLUNTEER_REQUEST: "DELETE_VOLUNTEER_REQUEST",
  EXPORT_VOLUNTEER_REQUEST: "EXPORT_VOLUNTEER_REQUEST",

  // Talent Requests
  VIEW_TALENT_REQUEST: "VIEW_TALENT_REQUEST",
  CREATE_TALENT_REQUEST: "CREATE_TALENT_REQUEST", // add
  UPDATE_TALENT_REQUEST: "UPDATE_TALENT_REQUEST",
  DELETE_TALENT_REQUEST: "DELETE_TALENT_REQUEST",
  EXPORT_TALENT_REQUEST: "EXPORT_TALENT_REQUEST",

  // Enquiries
  VIEW_ENQUIRY: "VIEW_ENQUIRY",
  EXPORT_ENQUIRY: "EXPORT_ENQUIRY",

  // Testimonials
  VIEW_TESTIMONIALS: "VIEW_TESTIMONIALS",
  // VIEW_TESTIMONIALS: "manage_testimonials",
  CREATE_TESTIMONIALS: "CREATE_TESTIMONIALS",
  UPDATE_TESTIMONIALS: "UPDATE_TESTIMONIALS",
  DELETE_TESTIMONIALS: "DELETE_TESTIMONIALS",
  EXPORT_TESTIMONIALS: "EXPORT_TESTIMONIALS",

  // Reports
  VIEW_REPORT: "VIEW_REPORT",
  CREATE_REPORT: "CREATE_REPORT",
  UPDATE_REPORT: "UPDATE_REPORT",
  DELETE_REPORT: "DELETE_REPORT",

  // Events
  VIEW_EVENT: "VIEW_EVENT",
  CREATE_EVENT: "CREATE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  DELETE_EVENT: "DELETE_EVENT",

  // Chapters
  VIEW_CHAPTER: "VIEW_CHAPTER",
  CREATE_CHAPTER: "CREATE_CHAPTER",
  UPDATE_CHAPTER: "UPDATE_CHAPTER",
  DELETE_CHAPTER: "DELETE_CHAPTER",

  // Chapter Categories
  VIEW_CHAPTERCATEGORY: "VIEW_CHAPTERCATEGORY",
  CREATE_CHAPTERCATEGORY: "CREATE_CHAPTERCATEGORY",
  UPDATE_CHAPTERCATEGORY: "UPDATE_CHAPTERCATEGORY",
  DELETE_CHAPTERCATEGORY: "DELETE_CHAPTERCATEGORY",

  // Schools (Academy + STEM-A-GIRL share same permission)
  VIEW_SCHOOL: "VIEW_SCHOOL",
  CREATE_SCHOOL: "CREATE_SCHOOL",
  UPDATE_SCHOOL: "UPDATE_SCHOOL",
  DELETE_SCHOOL: "DELETE_SCHOOL",

  // School Programs
  VIEW_SCHOOLPROGRAM: "VIEW_SCHOOLPROGRAM",
  CREATE_SCHOOLPROGRAM: "CREATE_SCHOOLPROGRAM",
  UPDATE_SCHOOLPROGRAM: "UPDATE_SCHOOLPROGRAM",
  DELETE_SCHOOLPROGRAM: "DELETE_SCHOOLPROGRAM",

  // Courses (Academy + STEM-A-GIRL share same permission)
  VIEW_COURSE: "VIEW_COURSE",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",

  // Success Stories (STEM-A-GIRL)
  VIEW_SUCCESS_STORY: "VIEW_SUCCESS_STORY",
  CREATE_SUCCESS_STORY: "CREATE_SUCCESS_STORY",
  UPDATE_SUCCESS_STORY: "UPDATE_SUCCESS_STORY",
  DELETE_SUCCESS_STORY: "DELETE_SUCCESS_STORY",

  // ========== Stem‑a‑Girl Modules ==========
  // Courses (STEM-A-GIRL)
  VIEW_SAG_COURSE: "VIEW_SAG_COURSE",
  CREATE_SAG_COURSE: "CREATE_SAG_COURSE",
  UPDATE_SAG_COURSE: "UPDATE_SAG_COURSE",
  DELETE_SAG_COURSE: "DELETE_SAG_COURSE",

  // Impact Stories (STEM-A-GIRL)
  VIEW_SAG_IMPACT_STORY: "VIEW_SAG_IMPACT_STORY",
  CREATE_SAG_IMPACT_STORY: "CREATE_SAG_IMPACT_STORY",
  UPDATE_SAG_IMPACT_STORY: "UPDATE_SAG_IMPACT_STORY",
  DELETE_SAG_IMPACT_STORY: "DELETE_SAG_IMPACT_STORY",

  // Outreach (STEM-A-GIRL)
  VIEW_SAG_OUTREACH: "VIEW_SAG_OUTREACH",
  CREATE_SAG_OUTREACH: "CREATE_SAG_OUTREACH",
  UPDATE_SAG_OUTREACH: "UPDATE_SAG_OUTREACH",
  DELETE_SAG_OUTREACH: "DELETE_SAG_OUTREACH",

  // Enquiries (STEM-A-GIRL)
  VIEW_SAG_ENQUIRY: "VIEW_SAG_ENQUIRY",
  UPDATE_SAG_ENQUIRY: "UPDATE_SAG_ENQUIRY",
  DELETE_SAG_ENQUIRY: "DELETE_SAG_ENQUIRY",

  // Activities (STEM-A-GIRL)
  VIEW_ACTIVITY: "VIEW_ACTIVITY",
  CREATE_ACTIVITY: "CREATE_ACTIVITY",
  UPDATE_ACTIVITY: "UPDATE_ACTIVITY",
  DELETE_ACTIVITY: "DELETE_ACTIVITY",

  // // Impact Stories (STEM-A-GIRL)
  // VIEW_IMPACT_STORIES: "VIEW_IMPACT_STORIES",
  // CREATE_IMPACT_STORIES: "CREATE_IMPACT_STORIES",
  // UPDATE_IMPACT_STORIES: "UPDATE_IMPACT_STORIES",
  // DELETE_IMPACT_STORIES: "DELETE_IMPACT_STORIES",

  // Initiatives
  VIEW_INITIATIVE: "VIEW_INITIATIVE",
  CREATE_INITIATIVE: "CREATE_INITIATIVE",
  UPDATE_INITIATIVE: "UPDATE_INITIATIVE",
  DELETE_INITIATIVE: "DELETE_INITIATIVE",

  // Partners
  VIEW_PARTNER: "VIEW_PARTNER",
  CREATE_PARTNER: "CREATE_PARTNER",
  UPDATE_PARTNER: "UPDATE_PARTNER",
  DELETE_PARTNER: "DELETE_PARTNER",

  // Our Reach
  VIEW_OUR_REACH: "VIEW_OUR_REACH",
  CREATE_OUR_REACH: "CREATE_OUR_REACH",
  UPDATE_OUR_REACH: "UPDATE_OUR_REACH",
  DELETE_OUR_REACH: "DELETE_OUR_REACH",

  // Users (Admin Settings)
  VIEW_USER: "VIEW_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  // Roles (Admin Settings)
  VIEW_ROLE: "VIEW_ROLE",
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",

  // Jobs
  VIEW_JOB: "VIEW_JOB",
  CREATE_JOB: "CREATE_JOB",
  UPDATE_JOB: "UPDATE_JOB",
  DELETE_JOB: "DELETE_JOB",

  // Companies
  VIEW_COMPANY: "VIEW_COMPANY",
  CREATE_COMPANY: "CREATE_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  DELETE_COMPANY: "DELETE_COMPANY",

  // Job Types
  VIEW_JOBTYPE: "VIEW_JOBTYPE",
  CREATE_JOBTYPE: "CREATE_JOBTYPE",
  UPDATE_JOBTYPE: "UPDATE_JOBTYPE",
  DELETE_JOBTYPE: "DELETE_JOBTYPE"
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;